name: Build, Sign, and Push Docker Image

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-image:latest .

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          # Ensure Homebrew is available in the current shell session
          echo "PATH=/home/linuxbrew/.linuxbrew/bin:$PATH" >> $GITHUB_ENV
          # Alternatively, you can use `brew` directly if available
          export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"

      - name: Install Notation CLI
        run: |
          # Make sure Homebrew is available in the current shell
          /home/linuxbrew/.linuxbrew/bin/brew install notation
          /home/linuxbrew/.linuxbrew/bin/notation version

      - name: Generate Test Key & Cert
        run: |
          /home/linuxbrew/.linuxbrew/bin/notation cert generate-test --default "wabbit-networks.io"

      - name: List Key and Cert
        run: |
          /home/linuxbrew/.linuxbrew/bin/notation key ls
          /home/linuxbrew/.linuxbrew/bin/notation cert ls

      - name: Sign Docker Image
        run: |
          /home/linuxbrew/.linuxbrew/bin/notation sign ${{ env.DIGEST }}

      - name: Show Image Signature
        run: |
          /home/linuxbrew/.linuxbrew/bin/notation ls ${{ env.DIGEST }}

      # - name: Create and Import Trust Policy
      #   run: |
      #     cat <<EOF > ./trustpolicy.json
      #     {
      #         "version": "1.0",
      #         "trustPolicies": [
      #             {
      #                 "name": "wabbit-networks-images",
      #                 "registryScopes": [ "*" ],
      #                 "signatureVerification": {
      #                     "level" : "strict"
      #                 },
      #                 "trustStores": [ "ca:wabbit-networks.io" ],
      #                 "trustedIdentities": [
      #                     "*"
      #                 ]
      #             }
      #         ]
      #     }
      #     EOF
      #     /home/linuxbrew/.linuxbrew/bin/notation policy import ./trustpolicy.json
      #     /home/linuxbrew/.linuxbrew/bin/notation policy show

      - name: Verify Docker Image
        run: |
          /home/linuxbrew/.linuxbrew/bin/notation verify ${{ env.DIGEST }}

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag and Push Signed Docker Image to Docker Hub
        run: |
          docker tag localhost:5001/my-image:v1 ${{ secrets.DOCKER_USERNAME }}/my-image:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-image:latest

      - name: List Docker Images
        run: docker images
